"""Canonical research cost assumptions.

Single source of truth for FBS spread assumptions. Previously duplicated in
scripts/poc_sb_stops.py (the table research_run.py actually read) and
tests/backtest/backtest_engine.py (a copy used by the legacy Backtester path).
Both copies covered only the original 11 symbols, so the three pairs adopted in
2026-07 could not be studied at all: pooled research_run hard-errors on a
symbol absent from the table, and the Backtester copy silently substituted 20
ticks.

Values are in BROKER TICKS. Convert with spread_price(); never multiply by
tick_size at call sites.
"""


class CostModelError(Exception):
    """A cost assumption is missing or unusable. Never guess a spread."""


# Indicative FBS spreads in broker ticks.
#   - The 11 incumbents carry the values used by the 2026-07-11 stop study and
#     the 2026-07-28 universe screen. Do not tune: changing one silently
#     re-bases every historical result quoted against it.
#   - US100 / ETHUSD / XTIUSD measured live over the Phase-1 HTTP bridge,
#     data/results/universe_screen_20260728/screen_candidates.py:29. XTIUSD
#     re-measured 2026-07-29 during the London/NY overlap (median 2 points,
#     n=20, zero variance) -- config/config.yaml:126-127.
FBS_SPREAD_TICKS = {
    "EURUSD": 8,
    "GBPUSD": 12,
    "USDJPY": 10,
    "AUDUSD": 10,
    "USDCAD": 12,
    "GBPCAD": 30,
    "GBPJPY": 25,
    "XAUUSD": 20,
    "US30": 200,
    "BTCUSD": 1000,
    "XBRUSD": 30,
    "US100": 200,
    "ETHUSD": 193,
    "XTIUSD": 2,
}


def spread_ticks(symbol):
    """Spread for `symbol` in broker ticks.

    Raises CostModelError rather than defaulting. A guessed spread produces a
    plausible-looking net R that is silently wrong, which is the failure mode
    this module exists to prevent.
    """
    try:
        return FBS_SPREAD_TICKS[symbol]
    except KeyError:
        raise CostModelError(
            f"no FBS spread assumption for {symbol!r}; "
            f"known: {sorted(FBS_SPREAD_TICKS)}"
        ) from None


def spread_price(symbol, tick_size):
    """Spread for `symbol` in PRICE units, given the broker's tick size."""
    ts = float(tick_size or 0.0)
    if ts <= 0:
        raise CostModelError(
            f"tick_size must be positive to price a spread for {symbol!r}, got {tick_size!r}"
        )
    return spread_ticks(symbol) * ts


# Broker tick specs for symbols that data/specs.json does not cover.
#
# data/specs.json is gitignored (.gitignore:21), machine-specific, and
# regenerated by scripts/cache_specs.py from a live MT5 bridge -- so the pairs
# adopted in 2026-07 have no reproducible spec, and research_run.py silently
# substituted EURUSD's (tick_size 1e-5, a 1000x error for an index). These
# values are the broker's own, read over the Phase-1 HTTP bridge and recorded in
# data/results/universe_screen_20260728/candidate_probe.json[sym]["info"].
#
# Deliberately does NOT duplicate any symbol data/specs.json already covers:
# two tables holding the same symbol would drift, and which one won would come
# down to lookup order. research_run.py prefers data/specs.json and consults
# this only as a fallback.
#
# XTIUSD is absent on purpose. candidate_probe.json["XTIUSD"] is null -- it was
# adopted after that probe run -- so its tick specs have never been read from
# the broker. Checking in the screen harness's hand-entered tick_value=10.0
# would launder a guess into a measurement. Unblock with scripts/cache_specs.py
# against a live bridge.
RESEARCH_TICK_SPECS = {
    "US100":  {"tick_value": 0.1, "tick_size": 0.01, "vol_min": 0.01, "vol_step": 0.01},
    "ETHUSD": {"tick_value": 0.1, "tick_size": 0.01, "vol_min": 0.01, "vol_step": 0.01},
}


def tick_spec(symbol):
    """Broker-probed tick spec for `symbol`, or None if we have never read one.

    Returns None rather than raising: whether a missing spec is fatal is the
    caller's decision, and research_run.py already owns it (--allow-default-spec).
    """
    spec = RESEARCH_TICK_SPECS.get(symbol)
    return dict(spec) if spec is not None else None
