"""Research clock reconciliation and conservative post-history snapshot assembly."""
from pathlib import Path

import numpy as np
import pandas as pd

CLOCKS = ('fixed_2', 'fixed_3', 'seasonal_eet')
OHLC = ['open', 'high', 'low', 'close']


def utc_from_broker(times, clock):
    index = pd.DatetimeIndex(times)
    if index.tz is not None:
        raise ValueError('expected naive broker-local timestamps')
    if clock == 'seasonal_eet':
        return index.tz_localize('Europe/Helsinki', ambiguous='NaT', nonexistent='NaT').tz_convert('UTC')
    if clock not in CLOCKS:
        raise ValueError('unknown broker clock')
    return index.tz_localize('UTC') - pd.Timedelta(hours=int(clock[-1]))


def select_ny(signals, minutes, clock, seen_dates=None):
    """First cost-eligible candidate per NY day; mutable seen_dates spans gaps."""
    dates = set() if seen_dates is None else seen_dates
    times = pd.DatetimeIndex([s['time'] for s in signals])+pd.Timedelta(minutes=minutes)
    ny = utc_from_broker(times, clock).tz_convert('America/New_York')
    out = []
    for signal, close in zip(signals, ny):
        if pd.isna(close) or close.hour != 10 or close.date() in dates:
            continue
        dates.add(close.date())
        out.append(signal)
    return out


def assemble_snapshots(files, after):
    """Discard forming/conflicting/invalid bars, then split at every M5 hole.

    Directory names are UTC capture times generated by _snapshot_warmup.
    Original CSVs are untouched. Returned segments are ascending and complete.
    """
    pieces = []
    stats = dict(files=len(files), rows=0, forming_or_ambiguous=0, invalid=0,
                 before_cutoff=0, conflicting_times=0, duplicate_rows=0)
    for filename in files:
        filename = Path(filename)
        capture = pd.to_datetime(filename.parent.name, format='%Y%m%d-%H%M%S', utc=True)
        frame = pd.read_csv(filename, usecols=['time', *OHLC])
        frame['time'] = pd.to_datetime(frame.time, errors='coerce')
        stats['rows'] += len(frame)
        closes = utc_from_broker(pd.DatetimeIndex(frame.time)+pd.Timedelta(minutes=5), 'seasonal_eet')
        complete = np.asarray(closes.notna() & (closes <= capture))
        stats['forming_or_ambiguous'] += int((~complete).sum())
        frame = frame[complete].copy()
        numeric = frame[OHLC].apply(pd.to_numeric, errors='coerce')
        valid = (np.isfinite(numeric).all(axis=1) & (numeric>0).all(axis=1)
                 & (numeric.high >= numeric[['open','close']].max(axis=1))
                 & (numeric.low <= numeric[['open','close']].min(axis=1)))
        valid &= frame.time.to_numpy(dtype='datetime64[ns]').astype('int64') % (300*10**9) == 0
        stats['invalid'] += int((~valid).sum())
        frame[OHLC] = numeric
        frame = frame[valid]
        stats['before_cutoff'] += int((frame.time <= pd.Timestamp(after)).sum())
        pieces.append(frame[frame.time > pd.Timestamp(after)])
    if not pieces:
        return [], {**stats, 'unique_bars':0, 'segments':0}
    data = pd.concat(pieces, ignore_index=True)
    conflicts = data.groupby('time')[OHLC].nunique().max(axis=1) > 1
    bad_times = conflicts[conflicts].index
    stats['conflicting_times'] = len(bad_times)
    data = data[~data.time.isin(bad_times)]
    before = len(data)
    data = data.drop_duplicates('time').sort_values('time').reset_index(drop=True)
    stats['duplicate_rows'] = before-len(data)
    groups = data.time.diff().ne(pd.Timedelta(minutes=5)).cumsum()
    segments = [group.reset_index(drop=True) for _, group in data.groupby(groups)]
    stats.update(unique_bars=len(data), segments=len(segments))
    return segments, stats
