"""Abstract Broker protocol — the seam. Trading code depends only on this + types.
All methods async; datetimes UTC; prices float; volume in lots. Reads raise BrokerError
subclasses on failure; writes return OrderResult(success=False) on broker rejection."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol, runtime_checkable

from .types import (
    Account, Candle, HealthStatus, MarketOrderRequest, Order, OrderResult,
    PendingOrderRequest, Position, SymbolInfo, Tick, Timeframe,
)


@runtime_checkable
class Broker(Protocol):
    async def health_check(self) -> HealthStatus: ...
    async def get_account(self) -> Account: ...
    async def get_symbol_info(self, symbol: str) -> SymbolInfo: ...
    async def get_candles(self, symbol: str, timeframe: Timeframe, count: int) -> list[Candle]: ...
    async def get_candles_range(self, symbol: str, timeframe: Timeframe,
                                from_dt: datetime, to_dt: datetime) -> list[Candle]: ...
    async def get_current_tick(self, symbol: str) -> Tick: ...
    async def get_open_positions(self) -> list[Position]: ...
    async def get_pending_orders(self) -> list[Order]: ...
    async def place_market_order(self, request: MarketOrderRequest) -> OrderResult: ...
    async def place_pending_order(self, request: PendingOrderRequest) -> OrderResult: ...
    async def modify_position(self, ticket: int, sl: float | None = None,
                              tp: float | None = None) -> OrderResult: ...
    async def close_position(self, ticket: int, volume: float | None = None) -> OrderResult: ...
    async def cancel_order(self, ticket: int) -> OrderResult: ...
